### PR TITLE
Crosspost, reply, dark mode fixes

### PR DESCRIPTION
**Pull request by 33mhz**
I recommend merging in one commit. -_-

### CODE REVIEW

**Comment by sunya9** [comment]
@33mhz Oh my gosh, forgot this PR. I recently have ended up updating Compose.vue... I'm very sorry but could you resolve conflicts?

**Comment by 33mhz** [comment]
I'll take a look at it in a few hours.

**Comment by 33mhz** [comment]
@sunya9 `setCaret()` was taken out of Beta in 1.9.2. I put it back in, but didn't consider cases (though it's only actually used once). You may want to put `setCaret()` back in somewhere else.

**Comment by 33mhz** [comment]
Just need to update the tests.

**Pull request merged**
